### ISSUE TITLE
Bloodmoon lightning rods

### ISSUE THREAD

**Issue by Bababooi-Baba-Yaga** [Latch93/DiscordText#25]
During a bloodmoon when lightning strikes a building, it completely ignores the various lightning rods on the building.

![image_2022-07-07_231148838](https://user-images.githubusercontent.com/108927585/177959164-54a15c91-7082-4c3b-9094-7857276ffcd7.png)

![lightning bloodmoon damage](https://user-images.githubusercontent.com/108927585/177959185-0da8ffba-3e55-49d2-a44e-a138b4f0d9ee.PNG)

**Comment by Latch93** [comment]
I'll look into this, but the bloodmoon isn't my code and is in alpha. Also, its not very configurable.

**Comment by Latch93** [comment]
I've gotten the source code finally of the bloodmoon plugin. Looking for solutions, but I should be able to disable lightning for the time being until I find it

**Comment by Latch93** [comment]
I've removed lightning strikes from bloodmoons
