### ISSUE TITLE
Show all shop items

### ISSUE THREAD

**Issue by Bababooi-Baba-Yaga** [Latch93/DiscordText#26]
Somewhere we can see what everyone has on their shop. The more people that join, the more time consuming and just a bit tedious it becomes to type /ps open (player name) for 15+ people.

You mentioned how maybe we can get the list of things in each players shop as a discord dm. That sounded like a great solution.

**Comment by Latch93** [comment]
I've gotten playershop search channel up and running in discord and while it's not 100%, seems to do the trick
