### ISSUE TITLE
Suggestion: Add Recycle Gear

### ISSUE THREAD

**Issue by Latch93** [Latch93/DiscordText#27]
Maybe make it so you can recycle old gear you dont need e.g old gold armour you can recycle to get some stuff back?
@Hodgetts24

**Comment by Hodgetts24** [comment]
basically, when u farm for a ton of items and you no longer need old or items that can be deemed as useless maybe add something that you can recycle the items and get a fraction of the items back so say if it was a pickaxe half hp u get half the materials u used so it would be like 1 gold and a few nuggets.

**Comment by Latch93** [comment]
That is a lot of logic to add, so I'm not sure. You can sell those items to the server. I know about the logic to accomplish this because I have an uncrafting plugin I made years ago which is actually on LMP, but it's disabled. Getting item recipes are very weird. So I don't think I'll add this, but you never know

**Comment by Bababooi-Baba-Yaga** [comment]
Not a complete solution and not a great return on resources, but you can put gold-iron armor or tools in a furnace and it'll give you a nugget, not much but its something

**Comment by Latch93** [comment]
Closing
