### ISSUE TITLE
suggestion: buy exp 

### ISSUE THREAD

**Issue by Hodgetts24** [Latch93/DiscordText#28]
try to make it so in the lmp shop you can buy exp levels for the in game currency :D

**Comment by Latch93** [comment]
I like this idea. Looking to add a sign at spawn to buy xp, or bring in the old xp shop POI from season 1

**Comment by Bababooi-Baba-Yaga** [comment]
Bottle O' Enchanting?

**Comment by Latch93** [comment]
Added XP shop to spawn
