### ISSUE TITLE
Spawners not "spawning"

### ISSUE THREAD

**Issue by Bababooi-Baba-Yaga** [Latch93/DiscordText#30]
None of my spawners are spawning anything, 9:25 pm HST monday if the time helps with anything

**Comment by Latch93** [comment]
This might be related to the logic that disables spawners during a bloodmoon. Time kind of tracks and I think it was due to my newly added midnight cst hard bloodmoon for you. Should be resolved

**Comment by Latch93** [comment]
Enabled Spawners during bloodmoons again as only mobs spawned in by the bloodmoon drop bonus drops
