### ISSUE TITLE
Wanted bounty on players if they steal from people's chest

### ISSUE THREAD

**Issue by StepBroJayy** [Latch93/DiscordText#31]
If someone steals from another persons chest, they should then get automatically wanted and their pvp gets turned on.

**Comment by Latch93** [comment]
A Bounty System. I can make it so players in a certain permission group get notified if a player takes an item from their chests, or a specific chest. Then I can make it so the wanted player can't use teleportation in any capacity, and hunters can pay a fee to get distance from the hunted.

**Comment by Bababooi-Baba-Yaga** [comment]
this sounds awesome
