### ISSUE TITLE
Player heads not dropping

### ISSUE THREAD

**Issue by Bababooi-Baba-Yaga** [Latch93/DiscordText#32]
Lindor and I both died 100+ times each, no player heads

**Comment by Bababooi-Baba-Yaga** [comment]
sleep

**Comment by Bababooi-Baba-Yaga** [comment]
solved, but now they drop every time we die

**Comment by Latch93** [comment]
Done, they only drop 5% of the time I think

**Comment by Bababooi-Baba-Yaga** [comment]
still drop everytime i die

**Comment by Latch93** [comment]
Should now be if a player dies to another player. Hopefully its 5 %

**Comment by Latch93** [comment]
Just updated to 5% drop, but only potentially drops if killed by another player

**Comment by Latch93** [comment]
Solved
