### ISSUE TITLE
Items in random item gen that dont drop anything

### ISSUE THREAD

**Issue by Bababooi-Baba-Yaga** [Latch93/DiscordText#33]
ill keep making a list in comments:
-Nether Portal
-Bubble Column

**Comment by Bababooi-Baba-Yaga** [comment]
-Potted Red Mushroom

**Comment by Bababooi-Baba-Yaga** [comment]
Soul Wall Torch

**Comment by Bababooi-Baba-Yaga** [comment]
-Wither skeleton wall skull
-Powder snow cauldron

**Comment by Bababooi-Baba-Yaga** [comment]
-Spruce Wall sign (i got 2, not item -.-)
-Void Air
-Potted Dandelion
-Wall torch
...getting kinda ridiculous...

**Comment by Bababooi-Baba-Yaga** [comment]
-Bubble Column (again)
-Powder Snow

**Comment by Bababooi-Baba-Yaga** [comment]
-Potted Pink Tulip
-Green Candle Cake
-Potted Dark Oak Sapling

**Comment by Latch93** [comment]
I think we are good with the current list, going to leave this open to catch more until 3 Tier RIG is implemented
