### ISSUE TITLE
Keep inv bug 

### ISSUE THREAD

**Issue by Frogking2** [Latch93/DiscordText#34]
![Screenshot_20220718-104010](https://user-images.githubusercontent.com/101676201/179538317-f03b6a8c-28a8-4faa-bdb9-34660bc7733a.png)

**Comment by DoctorLettuce** [comment]
I verified it on the server using my bedrock alt

-Messier

**Comment by Latch93** [comment]
This isn't a bug. I didn't announce this, but keepinv in the overworld is on until Tuesday and LTS is updated. This was done along with player money loss on death so players had a better chance of getting the pickaxe in the LTS. You should still be careful in not dying, so I only did it in the overworld

**Comment by Latch93** [comment]
closing this as it is a non issue and confusion
