### ISSUE TITLE
making a warzone 

### ISSUE THREAD

**Issue by Hodgetts24** [Latch93/DiscordText#39]
maybe making it so there is a zone at spawn where pvp is always enabled and if you die in there people can loot ur things as a risk for going in there u can gain or loose :D

**Comment by Latch93** [comment]
So I've thought about in the past was making an arena, where 2 players enter, and place a bet on the match. Winner get's the prize. I could do that with an item as well perhaps. Anyone is free to build the arena. I will be moving over and configuring the boss arena from season 4 within the next couple weeks
