### ISSUE TITLE
Hostile mob spawning changed back to pre-1.18 lighting configurations

### ISSUE THREAD

**Issue by DoctorLettuce** [Latch93/DiscordText#40]
Pre-1.18 mob spawning required a light level of 7 or less to spawn. In 1.18 that number was changed to a light level of 0. Is this by intention, or a bug?

**Comment by Latch93** [comment]
I intentionally coded it to be a level level of 7 or less, when a bloodmoon is not active. This only is set for mobs found in vanilla spawners

**Comment by DoctorLettuce** [comment]
Ight. Gotta light my base up like mad again :/

**Comment by Latch93** [comment]
Because of the way the config it for the server, they were spawning at what seemed to be light level greater than 7, which would cause creepers to spawn near a player with the base lit up, blowing them up. So I coded that out
